apiVersion: v1
kind: Pod
metadata:
  name: asl
spec:
  containers:
  - name: asl-container
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["sleep infinity"]
    volumeMounts:
    - name: dataset
      mountPath: /root/dataset
    - name: persistent
      mountPath: /root/persistent
    # - mountPath: /dev/shm
    #   name: dshm
    resources:
      limits:
        memory: 8Gi
        cpu: "2"
        # nvidia.com/gpu: 1
        ephemeral-storage: 30Gi
      requests:
        memory: 8Gi
        cpu: "2"
        # nvidia.com/gpu: 1
        ephemeral-storage: 20Gi
  volumes:
  - name: dataset
    persistentVolumeClaim:
      claimName: asl-dataset
  - name: persistent
    persistentVolumeClaim:
      claimName: asl-persistent
  # - name: dshm
  #   emptyDir:
  #     medium: Memory
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nvidia.com/gpu.product
  #           operator: In
  #           values:
  #           - NVIDIA-GeForce-RTX-3090
  restartPolicy: Never