apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asl-persistent
  namespace: autoslug
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
